carts/urls.py
from django.conf.urls import url

from .views import (
   cart_home,
   cart_update,
   checkout_home,
   checkout_done_view
   )

urlpatterns = [

    url(r'^$', cart_home, name='home' ),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),

]

dansite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from addresses.views import checkout_address_create_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from accounts.views import guest_register_view
from products.views import FeaturedListView

from .views import home_page, about_page, login_page, logout_page, register_page
urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', logout_page, name='logout'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^register/$', register_page, name='register'),
    url(r'^featured/$', FeaturedListView.as_view(), name='featured' ),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^admin/', admin.site.urls),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from .views import (
   ProductListView,
   FeaturedListView,
   ProductDetailSlugView,

   )

urlpatterns = [

    url(r'^$', ProductListView.as_view(), name='list' ),
    url(r'^featured/$', FeaturedListView.as_view(), name='featured' ),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),

]

templates/about_page.html
{% include 'base.html' %}
<h1 class="text-center">About Us</h1>

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>Ecommerce</title>
  </head>

  <body>
    {% include 'navbar.html' %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>

</html>

templates/card.html
<div class="card" style="width: 20rem;">
  {% if instance.image %}
    <a href="{{ instance.get_absolute_url }}"><img class="card-img-top" src="{{ instance.image.url }}" alt="{{ instance.title}}"></a>
    {% endif %}
  <div class="card-body">
    <h4 class="card-title">{{ instance.title }}</h4>
    <p class="card-text">{{ instance.description|linebreaks|truncatewords:14 }}</p>
    <a href="{{ instance.get_absolute_url }}" class="btn btn-primary">View</a>

  </div>
</div>

templates/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

<!-- Fontawesome CSS -->
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

templates/detail.html
{% include "base.html" %}

{% block content %}

  <div class='row'>
    <div class='col-12 col-md-6'>
      <h1>{{ object.title }}</h1>
      {{ object.timestamp|timesince }} ago
      {{ object.description|linebreaks }} <br/>
      {% if object.image %}
        <img src='{{ object.image.url }}' class='img-fluid'/>
      {% endif %}
    </div>
    <div class='col-12 col-md-6'>
        {% include 'update-cart.html' with product=object cart=cart %}


    </div>
  </div>

{% endblock %}

templates/featured.html
<div class="">
  <h2 class='text-center'>Featured</h2>
    <div class='row'>

      {% for obj in featured_products %}
        <div class='col'>
          {{ forloop.counter }}
          {% include 'card.html'  with instance=obj %}
          {% if forloop.counter|divisibleby:4 %}
        </div></div><div class='row'><div class='col-12'><hr/></div>
      {% elif forloop.counter|divisibleby:4 %}

        </div><div class='row'><div class='col-12'></div>

      {% else %}
        </div>
      {% endif %}


     {% endfor %}

</div>

templates/form.html
  <form method='POST' action='{% if action_url %}{{ action_url }}{% else %}{% url "login" %}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form }}
  <button type='submit' class='btn btn-default btn-lg col-2 justify-content-center'>Submit</button>
</form>

templates/home_page.html
{% include 'base.html' %}

<style>
  body {
    background-color: lightgrey;
  }
  .jumbotron{
  background-color: #F0FFFF;
	background-image: url('static/assets/images/project1.jpg');
	background-size: cover;
	background-repeat: no-repeat;
  background-position: center center;
  height: 425px;


}

</style>
  <body>
      <div class="container-fluid mt-5">
        <div class="jumbotron text-center text-white bg-dark">
          <h1 class="display-4">Welcome to the East African Shop</h1>
          <h3 class="lead">The sastisfaction you need at affordable prices</h3>
          <hr class="my-4">
          <p>Choose from a wide range of products in stock</p>
          <a class="btn btn-primary btn-lg" href="register" role="button">Sign Up</a>
        </div>
        <h3 class="text-center">Featured</h3>

        <div class="card-deck mb-5">
  <div class="card">
    <img src="static/assets/images/ecomm22.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <img src="static/assets/images/ecomm16.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <img src="static/assets/images/ecomm14.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>

    </div>

  </body>

</html>

templates/list.html
{% include "base.html" %}

{% block content %}
  <div class='row'>

    {% for obj in object_list %}
      <div class='col'>
        {{ forloop.counter }}
        {% include 'card.html'  with instance=obj %}
        {% if forloop.counter|divisibleby:4 %}
      </div></div><div class='row'><div class='col-12'><hr/></div>
    {% elif forloop.counter|divisibleby:4 %}

      </div><div class='row'><div class='col-12'></div>

    {% else %}
      </div>
    {% endif %}


   {% endfor %}



{% endblock %}

templates/login.html
{% include 'base.html' %}
<style>
body {
  background-color: lightgrey
}
</style>

{% block content %}
<h1 class="text-center">Login</h1>
<div class="container mt-4">
  <div class="row justify-content-start">
    <div class="col">
  <div class="col justify-content-center">
      <div class="form-group col">

        <form method='POST' class= "shadow p-3 mb-3 bg-info rounded"> {% csrf_token %}
          {{ form.as_p }}
          <button type='submit' class='btn btn-outline-light btn-lg col-2 justify-content-center'>Submit</button>
        </form>
      </div>
      </div>
    </div>
  </div>
  </div>
 </div>

{% endblock %}

templates/navbar.html
{% load static %}

{% url 'products:list' as product_list_url %}
{% url 'about' as about %}
{% url 'logout' as logout %}
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'cart:home' as cart_url %}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    <img src="{% static 'assets/images/logo2.png' %}" width="50" height="50" alt="" loading="lazy">
  </a>
  <a class="navbar-brand" href="{% url 'home' %}">Ecommerce</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item{% if request.path == product_url %}active{% endif %}">
        <a class="nav-link" href="{{ product_list_url }}">Products</a>
      </li>
      <li class="nav-item{% if request.path == about %}active{% endif %}">
        <a class="nav-link" href="{% url 'about' %}">About Us</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{{ cart_url}}">{{ request.session.cart_items }} <i class="fa fa-shopping-cart" aria-hidden="true"></i> </a>
      </li>

    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</nav>

templates/register.html
{% include "base.html" %}
<style>
body {
  background-color: lightgrey
}
</style>

{% block content %}
  <h1 class="text-center">Sign Up</h1>
  <div class="container">
  <div class="d-flex flex-column">
  <form method='POST'class= "shadow p-3 mb-3 bg-info rounded"> {% csrf_token %}
    {{ form.as_p }}
  <button type='submit' class='btn btn-outline-light btn-lg col-2 justify-content-center'>Submit</button>
  </form>

  </div>
  </div>

{% endblock %}

templates/update-cart.html
<form method='POST' action='{% url "cart:update" %}' class="form"> {% csrf_token %}
    <input type='hidden' name='product_id' value='{{ product.id }}' />

    {% if in_cart %}
        <button type='submit' class='btn btn-link btn-sm' style="padding:0px;cursor: pointer;">Remove?</button>
    {% else %}
        {% if product in cart.products.all %}
            In cart <button type='submit' class='btn btn-link'>Remove?</button>
        {% else %}
            <button type='submit'  class='btn btn-success'>Add to cart</button>
        {% endif %}
    {% endif %}
</form>